clan_site/basic/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views

app_name='basic'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),

    
    url(r'^users/$', login_required(views.UsersView.as_view()), name='users'),
    url(r'^users/(?P<pk>[0-9]+)/$', login_required(views.DetailView.as_view()), name='user_detail'),

    url(r'^rules/$', login_required(views.RulesView.as_view()), name='rules'),
    url(r'^rules/(?P<pk>[0-9]+)/$', login_required(views.RulesDetailView.as_view()), name='rule_detail'),
    url(r'^rules/add_rule$', views.add_rule, name='add_rule'),

    url(r'^register_handle/$', views.register_handle, name='register_handle'),
    url(r'^login_handle/$', views.login_handle,name='login_handle'),
    url(r'^logout$', views.logout_view, name='logout'),
]

clan_site/clan_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from basic import views


urlpatterns = [
    url('^register/', CreateView.as_view(
            template_name='registration/register.html',
            form_class=UserCreationForm,
            success_url='/'), name='register'),
    url('^accounts/', include('django.contrib.auth.urls')),


    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^basic/', include('basic.urls')),
    url(r'^battles/', include('battles.urls')),
    url(r'^memberSchedule/', include('memberSchedule.urls')),

    url(r'^admin/', admin.site.urls),
]

clan_site/memberSchedule/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views

app_name='memberSchedule'

urlpatterns = [
    url(r'^$', login_required(views.ScheduleIndexView.as_view()), name='schedule'),
    url(r'^add_availability/$', views.add_availability, name='add_availability'),
    # url(r'^add_inavailability/$', views.add_inavailability.as_view(), name='add_inavailability')
]

clan_site/memberSchedule/models.py
from django.db import models
from basic.models import Member


class Schedule(models.Model):
    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    available = models.DateTimeField()

clan_site/memberSchedule/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.contrib.auth.decorators import login_required

from basic.models import *
from .models import *

import datetime

# from .forms import *


class ScheduleIndexView(generic.ListView):
    template_name = 'memberSchedule/index.html'

    def get_queryset(self):
        return '';


@login_required
def add_availability(request):
    if request.method == 'POST':
        start, end, day = request.POST['start_time'], request.POST['end_time'], request.POST['day']

        m = Member.objects.get(username=request.user.get_username())
        # d = datetime.datetime(day, start, end) todo
        s = Schedule(member=m,available=timezone.now)
        # s.save()

    else:
        form = RulesForm()

    return render(request, ScheduleIndexView.template_name)

clan_site/memberSchedule/templates/memberSchedule/index.html
{% load staticfiles %}

<link rel='stylesheet' href="{% static 'memberSchedule/cal/fullcalendar.css' %}" />
<script src="{% static 'memberSchedule/cal/lib/jquery.min.js' %}"></script>
<script src="{% static 'memberSchedule/cal/lib/moment.min.js' %}"></script>
<script src="{% static 'memberSchedule/cal/fullcalendar.js' %}"></script>
<h2><i>Enter the dates, in which you are available</i></h2>

<div id='calendar'></div>


<script> 
$(function() {
    // page is now ready, initialize the calendar...
   $('#calendar').fullCalendar({
    editable: true,
    weekNumbers:true,
    eventClick: function() {
    },
    dayClick: function(date, jsEvent, view) {

        // alert(date.format())

        var start = prompt('Start time: (hh:mm)' ),
            end   = prompt('End time: (hh:mm)'),
            daySquare = $(this);

        if (start != null && end !=null) {
            $.post({
                url: "{% url 'memberSchedule:add_availability' %}",
                data: {
                    'day':  date.format(),
                    'start_time': start,
                    'end_time': end,
                     csrfmiddlewaretoken: '{{ csrf_token }}'
                },
                success: function(data) {
                     daySquare.css('background-color', 'blue');
                }
            });
        }else{
            alert('Fill both end and start time')
        }

    }
});

});
</script>