clan_site/basic/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views

app_name='basic'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),

    
    url(r'^users/$', login_required(views.UsersView.as_view()), name='users'),
    url(r'^users/(?P<pk>[0-9]+)/$', login_required(views.DetailView.as_view()), name='user_detail'),

    url(r'^rules/$', login_required(views.RulesView.as_view()), name='rules'),
    url(r'^rules/(?P<pk>[0-9]+)/$', login_required(views.RulesDetailView.as_view()), name='rule_detail'),
    url(r'^rules/add_rule$', views.add_rule, name='add_rule'),

    url(r'^register_handle/$', views.register_handle, name='register_handle'),
    url(r'^login_handle/$', views.login_handle,name='login_handle'),
    url(r'^logout$', views.logout_view, name='logout'),
]

clan_site/battles/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views

app_name='battles'

urlpatterns = [
    url(r'^$', login_required(views.BattlesIndexView.as_view()), name='battles'),
    url(r'^clan_wars/$', login_required(views.ClanWarsView.as_view()), name='clan_wars'),
    url(r'^ter_battles/$', login_required(views.TerBattlesView.as_view()), name='ter_battles'),
    url(r'^clan_wars/(?P<pk>[0-9]+)/$', login_required(views.ClanWarDetailView.as_view()), name='clan_war_details'),
    url(r'^ter_battles/(?P<pk>[0-9]+)/$', login_required(views.TerBattleDetailView.as_view()), name='ter_battle_details'),
    url(r'^ter_battles/(?P<pk>[0-9]+)/$', views.assign_members, name='assign'),


    url(r'^add_territory_battle$', views.add_territory_battle, name='add_territory_battle'),
    url(r'^add_clan_war_battle$', views.add_clan_war_battle, name='add_clan_war_battle'),
    url(r'^add_hypothesis/(?P<battle_id>[0-9]+)/$', views.add_hypothesis, name='add_hypothesis'),

]

clan_site/clan_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from basic import views


urlpatterns = [
    url('^register/', CreateView.as_view(
            template_name='registration/register.html',
            form_class=UserCreationForm,
            success_url='/'), name='register'),
    url('^accounts/', include('django.contrib.auth.urls')),


    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^basic/', include('basic.urls')),
    url(r'^battles/', include('battles.urls')),
    url(r'^memberSchedule/', include('memberSchedule.urls')),

    url(r'^admin/', admin.site.urls),
]

clan_site/basic/models.py
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.db.models.query import QuerySet
from django.contrib.auth.models import User
from django.utils import timezone


class Member(User):
	MEMBER_CHOICES = (
			('M', 'Member'),
			('O', 'Officer'),
			('C', 'Co_leader'),
			('L', 'Leader'), 
		)
	user_type=models.CharField(
		max_length=1,
		choices=MEMBER_CHOICES
	)
	photo=models.ImageField(blank=True) #todo resize

	def __str__(self):
		return "{0} {1} with username: {2} and type: {3}".format(self.first_name,
		 self.last_name, self.username, self.user_type)


class Rules(models.Model):
	content = models.CharField(max_length=1000)
	created_by = models.ForeignKey(Member, null=True, on_delete=models.SET_NULL)
	date_created = models.DateTimeField(default=timezone.now)

	def setContent():
		pass
	def getContent():
		pass

	def __str__(self):
		return self.content

# ------------------------------------------

clan_site/basic/forms.py
from django import forms
from django.contrib.admin.widgets import AdminDateWidget 
from django.forms import ModelForm
from basic.models import *
from battles.models import *
from itertools import chain

class RulesForm(forms.Form):
    rule_content = forms.CharField(label='Rule', widget=forms.Textarea, max_length=1000)

clan_site/basic/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm

from .models import *
from .forms import *


class IndexView(generic.ListView):
    template_name = 'basic/index.html'

    def get_queryset(self):
        return '';

class UsersView(generic.ListView):
    template_name = 'basic/users.html'
    context_object_name = 'users'

    def get_queryset(self):
        return Member.objects.order_by('first_name')


class RulesView(generic.ListView):
    template_name = 'basic/rules.html'
    # context_object_name = 'rules'
    model = Rules

    def get_context_data(self, **kwargs):
        context = super(RulesView, self).get_context_data(**kwargs)
        context['rules'] = Rules.objects.all()
        context['form'] = RulesForm()
        return context

class RulesDetailView(generic.DetailView):
    model = Rules
    context_object_name='rule'
    template_name = 'basic/rules_detail.html'


class DetailView(generic.DetailView):
    model = Member
    context_object_name='user'
    template_name = 'basic/detail.html'



@login_required
def add_rule(request):
    if request.method == 'POST':
        form = RulesForm(request.POST)
        if form.is_valid():
            content = form.cleaned_data['rule_content']
            m  = Member.objects.get(username=request.user.get_username())
            new_rule = Rules(content=content, created_by=m)
            new_rule.save()
            return HttpResponseRedirect(reverse('basic:rules'))
    else:
        form = RulesForm()

    return render(request, 'basic/rules.html', {'form': form, 'rules': Rules.objects.all()})

  
def register_handle(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # form.save()
            # user = super(UserCreationForm, self).save(commit=False)
            # user.set_password(self.cleaned_data["password1"])
            # if commit:
                # user.save()
            m = Member(username=form.cleaned_data['username'], user_type="M")
            m.set_password(form.cleaned_data["password1"])
            m.save()
            return HttpResponseRedirect(reverse('login'))
            # return HttpResponseRedirect(reverse('basic:index'))

    else:
        form = UserCreationForm()

    return render(request, 'registration/register.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('login')



def login_handle(request):
    # if request.method != 'POST':
    #     raise Http404('Only POSTs are allowed')
    # try:
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            login(request, user)
            return HttpResponseRedirect(reverse('basic:index'))
        else:
            return HttpResponse("Your account have been disabled :(")
    else:
        return HttpResponse("Your username and password didn't match")

clan_site/basic/templates/basic/clan_wars.html
 {% if battles %}
    <ul>
    {% for batlle in battles %}
	<li><a href="{% url 'battles:clan_war_details' batlle.id %}">{{ batlle }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No battles are available.</p>
{% endif %}

<button id="add_clan_war">Add a new clan war</button>

<form action="{% url 'battles:add_clan_war_battle' %}" style="display:none" method="POST" id="new_clan_war_form">
{% csrf_token %}
{{clan_war_form.as_p}}
<input type="submit" value="Submit">
</form>	
<script src="https://code.jquery.com/jquery-1.10.2.js"></script>

<script>
$( "#add_clan_war" ).click(function() {
	$('#new_clan_war_form').show();
	$('#add_clan_war').hide();
})
</script>

clan_site/basic/templates/basic/detail.html
<h2>{{ user.get_full_name }}</h2>

<li>Photo: "{{ user.photo.name }}"</li>
{% load staticfiles %}
<li> Photo: <img src="{% static user.photo.name %}"></img> </li>


<li>Username: {{ user.get_username }}</li>
<li>Member's rank: {{ user.get_user_type_display }}</li>
<li>Date joined: {{ user.date_joined }}</li>

clan_site/basic/templates/basic/index.html
{% extends "base.html" %}
{% block title %} Welcome to Freedoom's clan site! {% endblock %}

clan_site/basic/templates/basic/register.html
<html>
<body>
	<form accept-charset="UTF-8" action="/registration" class="simple_form new_registration" id="new_registration" method="post">
		<div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" />
			<input name="authenticity_token" type="hidden" value="AuxSmyPcwptChVQmxl3BFyk2Hc16Wp/bD7G89HPxwMk=" />
		</div>

		<div class="input string required registration_fb_name">
			<label class="string required" for="registration_fb_name">Име във facebook:
				<abbr title="required">*</abbr>
			</label>
			<input aria-required="true" class="string required" id="registration_fb_name" name="registration[fb_name]" required="required" type="text" />
		</div>
		
		<div class="input email required registration_email"><label class="email required" for="registration_email">Електронна поща <abbr title="required">*</abbr></label><input aria-required="true" class="string email required" id="registration_email" name="registration[email]" required="required" type="email" /></div>
			<input name="commit" type="submit" value="Регистрирай ме" />
	</form>
</body>
</html>

clan_site/basic/templates/basic/rules.html
 {% if rules %}
    <ul>
    {% for rule in rules %}
        <li><a href="{% url 'basic:rule_detail' rule.id %}">{{ rule.content }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No rules are available.</p>
{% endif %}


<button id="add_rule">Add a new rule</button>
<form action="{% url 'basic:add_rule' %}" style="display:none" method="POST" id="new_rule_form">
{% csrf_token %}
{{form}}
<input type="submit" value="Submit">
</form>	

<script src="https://code.jquery.com/jquery-1.10.2.js"></script>

<script>
$( "#add_rule" ).click(function() {
	$('#new_rule_form').show();
})
</script>

clan_site/basic/templates/basic/rules_detail.html
<h2>{{ rule.content}}</h2>

<li>Created by: 
	{%if rule.created_by.get_full_name%}
		{{ rule.created_by.get_full_name }}
	{%else %}
		{{rule.created_by.get_username}}
	{%endif%}
	</li>

clan_site/basic/templates/basic/users.html
{% extends "base.html" %}

{% block title %}All members{% endblock %}


{% block content %}
     {% if users %}
        <ul>
        {% for user in users %}
            <li><a href="{% url 'basic:user_detail' user.id %}">{{ user.get_username }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No users are available.</p>
    {% endif %}
{% endblock %}