clan_site/basic/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views

app_name='basic'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),

    
    url(r'^users/$', login_required(views.UsersView.as_view()), name='users'),
    url(r'^users/(?P<pk>[0-9]+)/$', login_required(views.DetailView.as_view()), name='user_detail'),

    url(r'^rules/$', login_required(views.RulesView.as_view()), name='rules'),
    url(r'^rules/(?P<pk>[0-9]+)/$', login_required(views.RulesDetailView.as_view()), name='rule_detail'),
    url(r'^rules/add_rule$', views.add_rule, name='add_rule'),

    url(r'^register_handle/$', views.register_handle, name='register_handle'),
    url(r'^login_handle/$', views.login_handle,name='login_handle'),
    url(r'^logout$', views.logout_view, name='logout'),
]

clan_site/battles/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views

app_name='battles'

urlpatterns = [
    url(r'^$', login_required(views.BattlesIndexView.as_view()), name='battles'),
    url(r'^clan_wars/$', login_required(views.ClanWarsView.as_view()), name='clan_wars'),
    url(r'^ter_battles/$', login_required(views.TerBattlesView.as_view()), name='ter_battles'),
    url(r'^clan_wars/(?P<pk>[0-9]+)/$', login_required(views.ClanWarDetailView.as_view()), name='clan_war_details'),
    url(r'^ter_battles/(?P<pk>[0-9]+)/$', login_required(views.TerBattleDetailView.as_view()), name='ter_battle_details'),
    url(r'^ter_battles/(?P<pk>[0-9]+)/$', views.assign_members, name='assign'),


    url(r'^add_territory_battle$', views.add_territory_battle, name='add_territory_battle'),
    url(r'^add_clan_war_battle$', views.add_clan_war_battle, name='add_clan_war_battle'),
    url(r'^add_hypothesis/(?P<battle_id>[0-9]+)/$', views.add_hypothesis, name='add_hypothesis'),

]

clan_site/clan_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from basic import views


urlpatterns = [
    url('^register/', CreateView.as_view(
            template_name='registration/register.html',
            form_class=UserCreationForm,
            success_url='/'), name='register'),
    url('^accounts/', include('django.contrib.auth.urls')),


    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^basic/', include('basic.urls')),
    url(r'^battles/', include('battles.urls')),
    url(r'^memberSchedule/', include('memberSchedule.urls')),

    url(r'^admin/', admin.site.urls),
]

clan_site/battles/models.py
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.db.models.query import QuerySet
from basic.models import Member
import datetime


class Territory(models.Model):
    PLANET_CHOICES = (
        ('S', 'Syra'),
        ('T', 'Terra')
    )

    planet=models.CharField(max_length=1, choices=PLANET_CHOICES)
    name=models.CharField(max_length=50)
    time_for_preparation=models.DurationField(blank=True, null=True) #todo to be: models.DurationField?
    time_for_battle=models.DurationField(blank=True, null=True)

    def get_name(self):
        return self.name

    def __str__(self):
        return "{0}/{1}.".format(self.get_planet_display(), self.name)

class Battle(models.Model):
    STATUS_CHOICES = (
            ('O', 'Open'),
            ('C', 'Closed'),
            ('F', 'Future') 
        )

    date=models.DateField(default=datetime.date.today)
    status=models.CharField(
        max_length=1,
        choices=STATUS_CHOICES
    )

    class Meta:
        abstract = True


class TerritoryBattle(Battle):
   
    assigned_users = models.ManyToManyField(Member) #Maktia.assignedUsers.add('john')
    territory = models.ForeignKey(Territory, on_delete=models.PROTECT)
    # hypothesis = models.ManyToManyField(Hypothesis, default=0, blank=True)


    def __str__(self):
        return "Battle for " + str(self.territory)

    def calculateHypothesis():
        pass

class ClanWar(Battle):
    CLAN_WAR_TYPES = (
            ('XP', 'Experience'),
            ('RES', 'Resources'),
            ('DMG', 'Damage'),
            ('GL', 'Glory')
        )

    RESULT_CHOICES = (
            ('w', 'won'),
            ('l', 'lost'),
            ('p', 'proccesing')
        )

    war_type = models.CharField(
            max_length=3,
            choices=CLAN_WAR_TYPES)
    result = models.CharField(
        max_length=1,
        choices=RESULT_CHOICES)
    enemy_clans = models.CharField(max_length=120)


    def __str__(self):
        return "{0} war ({1})".format(self.get_war_type_display(),
         self.date)



class Hypothesis(models.Model):
    STAR_CHOICES = [(str(i), i) for i in range(0,4)]
    OPPONENTS = [i for i in range(1,11)]

    terittory_battle = models.ForeignKey(TerritoryBattle)
    teammate = models.ForeignKey(Member)
    opponent = models.PositiveSmallIntegerField()
    stars = models.CharField(max_length=1, choices=STAR_CHOICES)

    class Meta:
        unique_together = (("terittory_battle", "opponent", "stars"))


    def getHypothesis(self):
        return {self.teammate.get_username(): {self.opponent: self.stars}}

    def __str__(self):
        return str(self.terittory_battle) +" "+str(self.getHypothesis())

clan_site/battles/forms.py
from django import forms
from django.contrib.admin.widgets import AdminDateWidget 
from django.forms import ModelForm
from basic.models import *
from battles.models import *
from itertools import chain

def getMemberAsOptions():
	members = Member.objects.all()
	return [(member.id, member.get_username()) for member in members]

def getTerritoriesAsOptions():
	territories = Territory.objects.all()
	return [(terittory.id, terittory.get_name()) for terittory in territories]


# todo: modelForm!!!
class Battle(forms.Form):
	status = forms.ChoiceField(Battle.STATUS_CHOICES)
	date = forms.DateField(initial=datetime.date.today, widget=forms.SelectDateWidget)

class TerritoryBattleForm(Battle):
	assigned_users = forms.MultipleChoiceField(choices=getMemberAsOptions(), widget=forms.CheckboxSelectMultiple())
	planet=forms.ChoiceField(Territory.PLANET_CHOICES)
	territory=forms.ChoiceField(choices=getTerritoriesAsOptions())

class ClanWarForm(Battle):
	clan_war_type = forms.ChoiceField(ClanWar.CLAN_WAR_TYPES)
	result = forms.ChoiceField(ClanWar.RESULT_CHOICES)
	enemy_clans=forms.CharField(max_length=50)


class HypothesisForm(forms.Form):
	def __init__(self, *args, **kwargs):
	        super(HypothesisForm, self).__init__(*args, **kwargs)
	        for i in Hypothesis.OPPONENTS:
	            self.fields['opponent_' + str(i)] = forms.ChoiceField(Hypothesis.STAR_CHOICES)

clan_site/battles/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

from django.views import generic

from .models import *
from battles.forms import *

from itertools import chain

class BattlesIndexView(generic.ListView):
    template_name = 'battles/battles.html'

    def get_queryset(self):
        return '';


class ClanWarsView(generic.ListView):
    template_name = 'battles/clan_wars.html'
    model = ClanWar

    def get_context_data(self, **kwargs):
        context = super(ClanWarsView, self).get_context_data(**kwargs)
        context['battles'] = ClanWar.objects.all()
        context['clan_war_form'] = ClanWarForm()

        return context


class TerBattlesView(generic.ListView):
    template_name = 'battles/ter_battles.html'
    model = TerritoryBattle

    def get_context_data(self, **kwargs):
        context = super(TerBattlesView, self).get_context_data(**kwargs)
        context['battles'] = TerritoryBattle.objects.all()
        context['territory_form'] = TerritoryBattleForm()

        return context


class ClanWarDetailView(generic.DetailView):
    template_name='battles/clan_war_details.html'
    model = ClanWar
    context_object_name='battle'


class TerBattleDetailView(generic.DetailView):
    template_name='battles/ter_battle_detail.html'
    model = TerritoryBattle
    context_object_name='battle'

    def get_context_data(self, **kwargs):
        context = super(TerBattleDetailView, self).get_context_data(**kwargs)
        context['form'] = HypothesisForm()
        return context
  
@login_required
def add_territory_battle(request):
    if request.method == 'POST':
        form = TerritoryBattleForm(request.POST)
        if form.is_valid():
            status = form.cleaned_data['status']
            date = form.cleaned_data['date']
            assigned_users_ids=form.cleaned_data['assigned_users']
            assigned_users = [Member.objects.get(pk=user_id) for user_id in assigned_users_ids]
            # planet=form.cleaned_data['planet']
            terittory_id=form.cleaned_data['territory']
            terittory=Territory.objects.get(pk=terittory_id)

            new_territory_battle = TerritoryBattle(status=status, date=date, territory=terittory)
            new_territory_battle.save()

            for assigned_user in assigned_users:
                new_territory_battle.assigned_users.add(assigned_user)
            new_territory_battle.save()

            return HttpResponseRedirect(reverse('battles:ter_battles'))
    else:
        form = TerritoryBattleForm()

    return render(request, TerBattlesView.template_name, {'territory_form': form, 'battles': TerritoryBattle.objects.all()})
    #todo: Refactor!!!

@login_required
def add_clan_war_battle(request):
    if request.method == 'POST':
        form = ClanWarForm(request.POST)
        if form.is_valid():
            war_type = form.cleaned_data['clan_war_type']
            result = form.cleaned_data['result']
            enemy_clans=form.cleaned_data['enemy_clans']

            new_clan_war = ClanWar(war_type=war_type, result=result, enemy_clans=enemy_clans)
            new_clan_war.save()

            return HttpResponseRedirect(reverse('battles:clan_wars'))
    else:
        form = ClanWarForm()

    return render(request, ClanWarsView.template_name, {'clan_war_form': form, 'battles':ClanWar.objects.all()})
    # todo Refactor the 'battles'

@login_required
def add_hypothesis(request, battle_id):
    if request.method == 'POST':
        form = HypothesisForm(request.POST)
        if form.is_valid():
            battle = TerritoryBattle.objects.get(pk=battle_id)
            for i in Hypothesis.OPPONENTS:
                stars = form.cleaned_data['opponent_' + str(i)]
                
                m  = Member.objects.get(username=request.user.get_username())
                h = Hypothesis.objects.get_or_create(terittory_battle=battle, teammate=m, opponent=i)
                h[0].stars=stars
                h[0].save()

            return HttpResponseRedirect(reverse('battles:ter_battles'))
    else:
        form = HypothesisForm()

    return render(request, TerBattlesView.template_name, {'territory_form': form, 'battles': TerritoryBattle.objects.all()})
    #todo: Refactor!!!


@login_required
def assign_members(request, battle_id):
    return render(request, TerBattlesView.template_name, {'territory_form': form, 'battles': TerritoryBattle.objects.all()})
    #todo: Refactor!!!

clan_site/battles/templates/battles/battle_detail.html
<h2>{{ battle }} and type {{i}}</h2>

clan_site/battles/templates/battles/battles.html
<li> <a href="{% url 'battles:clan_wars' %}"> Clan wars </a></li>
<li> <a href="{% url 'battles:ter_battles'%}"> Teritory battles </a></li>



<!--  {% if battles %}
    <ul>
    {% for batlle in battles %}
	<li><a href="{% url 'battles:battle_details' batlle.id %}">{{ batlle }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No battles are available.</p>
{% endif %}


<button id="add_territory_battle">Add a new territory batlle</button>
<button id="add_clan_war">Add a new clan war</button>

<form action="{% url 'battles:add_territory_battle' %}" style="display:none" method="POST" id="new_battle_form">
{% csrf_token %}
{{territory_form.as_p}}
<input type="submit" value="Submit">
</form>	

<form action="{% url 'battles:add_clan_war_battle' %}" style="display:none" method="POST" id="new_clan_war_form">
{% csrf_token %}
{{clan_war_form.as_p}}
<input type="submit" value="Submit">
</form>	


<script src="https://code.jquery.com/jquery-1.10.2.js"></script>

<script>
$( "#add_territory_battle" ).click(function() {
	$('#new_battle_form').show();
	$('#add_territory_battle').hide();
	$('#add_clan_war').show();
	$('#new_clan_war_form').hide();
})

$( "#add_clan_war" ).click(function() {
	$('#new_clan_war_form').show();
	$('#add_clan_war').hide();
	$('#add_territory_battle').show();
	$('#new_battle_form').hide();
})
</script> -->

clan_site/battles/templates/battles/clan_war_details.html
<h2>{{ battle }} </h2>

clan_site/battles/templates/battles/clan_wars.html
 {% if battles %}
    <ul>
    {% for batlle in battles %}
	<li><a href="{% url 'battles:clan_war_details' batlle.id %}">{{ batlle }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No battles are available.</p>
{% endif %}

<button id="add_clan_war">Add a new clan war</button>

<form action="{% url 'battles:add_clan_war_battle' %}" style="display:none" method="POST" id="new_clan_war_form">
{% csrf_token %}
{{clan_war_form.as_p}}
<input type="submit" value="Submit">
</form>	
<script src="https://code.jquery.com/jquery-1.10.2.js"></script>

<script>
$( "#add_clan_war" ).click(function() {
	$('#new_clan_war_form').show();
	$('#add_clan_war').hide();
})
</script>

clan_site/battles/templates/battles/ter_battle_detail.html
<h2>{{ battle }} </h2>
<p>{{battle.get_status_display}}</p>
<label>Assigned users: 
{% for member in battle.assigned_users.all %}
	<li><a href="{% url 'basic:user_detail' member.id %}">{{ member.get_username }}</a></li>
{% endfor %}
</label>


{%ifequal battle.status 'O'%}
	<label>Hypothesis:</label>

	<form action="{% url 'battles:add_hypothesis' battle.id %}" method="POST" id="hypothesis_form">
		{% csrf_token %}
		{{form.as_p}}
		<input type="submit" value="Submit">
	</form>	
{%endifequal%}



<!-- todo: add to static! -->
<button id="auto_assign">Assign</button> 


<script src="https://code.jquery.com/jquery-1.10.2.js"></script>

<script>
    $( "#add_territory_battle" ).click(function() {
        $('#new_battle_form').show();
        $('#add_territory_battle').hide();
    });

    $('#auto_assign').click(function () {
        $.ajax({
          url: "{% url 'battles:assign' battle.id %}"
        }).success(function(data) {
          alert("Oh my" + data);
        });
    })

</script>

clan_site/battles/templates/battles/ter_battles.html
 {% if battles %}
    <ul>
    {% for batlle in battles %}
	<li><a href="{% url 'battles:ter_battle_details' batlle.id %}">{{ batlle }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No battles are available.</p>
{% endif %}


<button id="add_territory_battle">Add a new territory batlle</button>
<form action="{% url 'battles:add_territory_battle' %}" style="display:none" method="POST" id="new_battle_form">
{% csrf_token %}
{{territory_form.as_p}}
<input type="submit" value="Submit">
</form>	



<script src="https://code.jquery.com/jquery-1.10.2.js"></script>

<script>
$(function() {
    $( "#add_territory_battle" ).click(function() {
    	$('#new_battle_form').show();
    	$('#add_territory_battle').hide();
    	$('#add_clan_war').show();
    	$('#new_clan_war_form').hide();
    });
});
</script>